// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.choose_blocksize_1d(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.choose_blocksize_2d(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.findnth64(System.UInt64,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.popcnt64(System.UInt64)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedianFilter2d(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Double[],System.Double[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedianFilter1d(System.Int32,System.Int32,System.Int32,System.Double[],System.Double[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedianFilter2dCore(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Double[],System.Double[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedianFilter1dCore(System.Int32,System.Int32,System.Int32,System.Double[],System.Double[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Dim.calc_step(System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Dim.calc_count(System.Int32,System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.BDim.set(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.BDim.w0(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.BDim.w1(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Window.clear")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Window.update(System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Window.size~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Window.find(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.Window.get_words(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.WindowRank.init_start")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.WindowRank.init_feed(System.Double,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.WindowRank.init_finish")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.WindowRank.clear")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.WindowRank.update(System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.WindowRank.get_med~System.Double")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.run(System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.calc_rank")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.medians")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.pack(System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.coord(System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.run(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.calc_rank")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.medians")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.update_block(System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.pack(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.coord(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc1D.set_med(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.update_block(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:FrankHileman.MedianFilter2D.Filter.MedCalc2D.set_med(System.Int32,System.Int32)")]
